KOD-4.3-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #19
Opened 2022-10-17 15:12 UTC by artcor77

2022-10-17 18:23 UTC, mps4dev requested changes

2022-10-17 18:23 UTC, mps4dev commented on kodilla-collections/src/main/java/com/kodilla/collections/lists/homework/CarsListApplication.java
> +
Gdzie wyswietlenie ?

2022-10-17 18:40 UTC, artcor77 commented on kodilla-collections/src/main/java/com/kodilla/collections/lists/homework/CarsListApplication.java
> +
Skasowałem niepotrzebnie po zrobieniu drugiej for-each.

2022-10-18 15:00 UTC, mps4dev approved these changes

2022-10-18 18:38 UTC, merged