KOD-4.4-Zbiory-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #21
Opened 2022-10-17 16:20 UTC by artcor77

2022-10-17 18:24 UTC, mps4dev requested changes

2022-10-17 18:24 UTC, mps4dev commented on kodilla-collections/src/main/java/com/kodilla/collections/sets/homework/StampsApplication.java
> +        for (Stamp stamp : stamps) {
Jakies sprawdzenie, ze jest okej? Np if?

2022-10-17 18:52 UTC, artcor77 commented
Porównanie z docelowym rozmiarem zbioru wystarczy ?

2022-10-18 15:02 UTC, mps4dev requested changes

2022-10-18 15:02 UTC, mps4dev commented on kodilla-collections/src/main/java/com/kodilla/collections/sets/homework/StampsApplication.java
> +        for (Stamp stamp : stamps) {
Bez sensu ta petla 
Raczej if (size == 5)sout(“ok”)

2022-10-18 18:27 UTC, mps4dev approved these changes

2022-10-18 18:38 UTC, merged