KOD-5.4-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #27
Opened 2022-10-20 18:58 UTC by artcor77

2022-10-20 19:00 UTC, artcor77 commented
Jeszcze bez testów.  Metody OK ?

2022-10-21 15:24 UTC, artcor77 commented
Testy nie idą, jak trzeba...

2022-10-21 15:40 UTC, mps4dev requested changes

2022-10-21 15:40 UTC, mps4dev commented on kodilla-collections-advanced/src/test/java/com/kodilla/collections/adv/exercises/homework/FlightFinderTestSuite.java
> +        assertEquals(expectedList, departuresResult);
Mozna prosciej:
List.of(new Flight(),  new Flight())

2022-10-21 16:00 UTC, artcor77 commented on kodilla-collections-advanced/src/test/java/com/kodilla/collections/adv/exercises/homework/FlightFinderTestSuite.java
> +        assertEquals(expectedList, departuresResult);
Chodzi o taki zapis w sekcji //then ?
//then
        assertEquals(List.of(new Flight("WRO", "WAW"), new Flight("WRO", "GDA")), departuresResult);

2022-10-21 16:07 UTC, artcor77 commented on kodilla-collections-advanced/src/test/java/com/kodilla/collections/adv/exercises/homework/FlightFinderTestSuite.java
> +        assertEquals(expectedList, departuresResult);
Szukam jeszcze czegoś bo testy nie przechodżą:
**expected**: java.util.ImmutableCollections$List12@3ad83a66<[Flight{departure='WRO', arrival='WAW'}, Flight{departure='WRO', arrival='GDA'}]> 

**but was:** java.util.ArrayList@3cce5371<[Flight{departure='WRO', arrival='WAW'}, Flight{departure='WRO', arrival='GDA'}]>org.opentest4j.AssertionFailedError:

2022-10-21 17:28 UTC, mps4dev commented on kodilla-collections-advanced/src/test/java/com/kodilla/collections/adv/exercises/homework/FlightFinderTestSuite.java
> +        assertEquals(expectedList, departuresResult);
Tak, o to chodzi. 
nadpisz metody equals i hashCode

2022-10-21 19:30 UTC, artcor77 commented
Dzięki za podpowiedzi. Kod krótszy i testy zdane

2022-10-22 12:45 UTC, mps4dev approved these changes

2022-10-22 12:48 UTC, merged