KOD-6.3-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #33
Opened 2022-10-26 17:38 UTC by artcor77

2022-10-26 18:31 UTC, mps4dev requested changes

2022-10-26 18:31 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/homework/ForumStats.java
> +    public static double youngerGroup() {
public double getAverageNumberOfPostsInGroupOfUsersYoungerThan(List<User> users, int age) {

        double youngerGroup = UsersRepository.getUsersList()
                .stream()
                .filter(user -> user.getAge() < 40)
                .mapToDouble(n -> n.getNumberOfPost())
                .average()
                .getAsDouble();

        return youngerGroup;
    }

2022-10-26 18:31 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/homework/ForumStats.java
> +
List<User> users = UsersRepository.getUsersList();
System.out.println("Average ....: " + getAverageNumberOfPostsInGroupOfUsersYoungerThan(users, 40));

2022-10-26 18:31 UTC, mps4dev commented on kodilla-stream/src/test/java/com/kodilla/stream/homework/ForumStatsTest.java
> +
// given 
List<Usr> users = List.of(new User(), new User(), new User() ....)

2022-10-26 18:31 UTC, mps4dev commented on kodilla-stream/src/test/java/com/kodilla/stream/homework/ForumStatsTest.java
> +    }
dla pustej listy uzytkownikow

2022-10-26 18:31 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/homework/ForumStats.java
> +
usunac zbedne puste linie

2022-10-27 12:19 UTC, artcor77 commented
Co zmienić, żeby test był dla nowej listy, a nie z UsersRepository bo ciągle coś nie wychodzi ?

2022-10-27 15:14 UTC, mps4dev requested changes

2022-10-27 15:14 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/stream/homework/ForumStats.java
> +                .getAsDouble();
Lepiej uzywac orElse(0) - w przypadku pustego streami bedziemy mieli tu NullPointerException

2022-10-27 16:39 UTC, artcor77 commented on kodilla-stream/src/main/java/com/kodilla/stream/homework/ForumStats.java
> +                .getAsDouble();
Zakończyć w ten sposób ?
.average().orElse(0);
        return average;

2022-10-27 16:46 UTC, artcor77 commented on kodilla-stream/src/main/java/com/kodilla/stream/homework/ForumStats.java
> +                .getAsDouble();
Testy zdane łącznie z pustą listą

2022-10-28 17:50 UTC, mps4dev approved these changes

2022-10-28 19:34 UTC, merged