KOD-6.4-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #35
Opened 2022-10-27 16:27 UTC by artcor77

2022-10-28 15:29 UTC, artcor77 commented
Narazie OK ?   getOrder ma być List ? Inaczej mi nie wychodziło...

2022-10-28 17:52 UTC, mps4dev requested changes
A gdzie rzucanie wyjatku?

2022-10-28 17:52 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/exception/homework/Warehouse.java
> +        List<Order> newOrder = orders;
Nie rozumiem tej linijki

2022-10-28 17:52 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/exception/homework/Warehouse.java
> +
Co mamy zwrocic?

2022-10-29 16:43 UTC, artcor77 commented
Dodałem wyjątek, program działa poprawnie.

2022-10-29 17:02 UTC, mps4dev requested changes

2022-10-29 17:02 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/exception/homework/Warehouse.java
> +    public Order addOrder(Order order) {   //Dodaje zamówienia do listy
Po co tu zwracac Order?

2022-10-29 17:02 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/exception/homework/Warehouse.java
> +                .orElseThrow(OrderDoesntExistException::new);
Jest okej. Tylko jak dostaniesz taki wyjatek, to nie bedziesz wiedzial dlaczego. Warto dodac konstruktor do klasy wyjatku, ktory przyjmie stringa z numerem zamowienia.

public OrderNotFoubdExceprion(String orderNumber) {
    super(String.format(„Order with id %s does not exist”, orderNumber);
}

2022-10-29 17:02 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/exception/homework/WarehouseApp.java
> +            System.out.println("Sorry, this order is not exist");            //Jesli nieistnieje
system.out.println(e.getMesaage();

2022-10-29 21:10 UTC, artcor77 commented
Nie wiem, czy dobrz wprowadziłem te zmiany. W przypadku nieistniejącego zamówienia mam non-zero.

2022-10-30 17:31 UTC, mps4dev requested changes

2022-10-30 17:31 UTC, mps4dev commented on kodilla-stream/src/main/java/com/kodilla/exception/homework/Warehouse.java
> +                .orElseThrow();
Ale co throw???

2022-10-30 18:18 UTC, artcor77 commented
Nie wiedziałem, jak napisać to, ale teraz wyszło

2022-10-30 19:01 UTC, mps4dev approved these changes

2022-10-30 19:19 UTC, merged