KOD-7.2-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #41
Opened 2022-11-03 14:56 UTC by artcor77

2022-11-03 16:16 UTC, artcor77 commented
![image](https://user-images.githubusercontent.com/113117950/199775128-eb250151-e9b7-4082-a395-2e63f32da832.png)

2022-11-03 16:29 UTC, artcor77 commented
Sprawdziłem expected.size i tu jest błąd.... Testuje pierwsze cyfry

2022-11-03 16:33 UTC, artcor77 commented
I powinienem testować howManyWins, czy zrobic public validateNumbers() i to dawać ?

2022-11-03 20:32 UTC, mps4dev requested changes

2022-11-03 20:32 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/parametrized_tests/homework/GamblingMachineTestSuite.java
> +                .collect(Collectors.toSet());
gdzie tu jakas asercja? Np. ze wynik jest liczba z zakresu 0-6?

2022-11-04 14:30 UTC, artcor77 commented
Teraz za każdym razem testy zdane.

Wcześniej brało pod uwagę tylko pierwsze cyfry bo wiersze w csv nie zamykałem w cudzysłów... ;)

2022-11-04 15:54 UTC, mps4dev requested changes

2022-11-04 15:54 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/parametrized_tests/homework/GamblingMachineTestSuite.java
> +        if (count<1)
Co to jest?

2022-11-04 15:54 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/parametrized_tests/homework/GamblingMachineTestSuite.java
> +        assertTrue(expectedNumbers);
Tu ma byc asercja, ze count > 0 oraz ze count < 7

2022-11-05 14:30 UTC, artcor77 commented
Z count >= 0 działa za każdym razem

2022-11-05 16:30 UTC, mps4dev approved these changes

2022-11-05 19:12 UTC, merged