KOD-7.4-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #45
Opened 2022-11-08 16:15 UTC by artcor77

2022-11-09 18:23 UTC, mps4dev requested changes

2022-11-09 18:23 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +    Order a = new Order(250, LocalDate.of(2022,11,7), "Art07");
co to jest?

2022-11-09 18:23 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +        assertEquals(Set.of(e, g), shop.getOrderByValueRange(800, 2500.39)); //Powinna być delta ??
delta dla Set?

2022-11-09 18:23 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +        assertEquals(Set.of(e, g), shop.getOrderByValueRange(800.6, 800.6));
osobne testy beda lepsze

2022-11-09 19:11 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +    public void initializeShop() {
init()

2022-11-09 19:11 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +}
```
private static Shop initShop() {
   Shop shop = new Shop();
    Order a = new Order(250, LocalDate.of(2022,11,7), "Art07");
Order b = new Order(50.50, LocalDate.of(2022,5,10), "Bar12");
    Order c = new Order(2500.40, LocalDate.of(2022,2,15), "ano");
    Order d = new Order(300, LocalDate.of(2021,1,30), "mar20");
    Order e = new Order(800.60, LocalDate.of(2020,12,1), "bet56");
    Order f = new Order(300, LocalDate.of(2021,1,30), "mar20");
    Order g = new Order(800.60, LocalDate.of(2020,12,1), "bet56");
    shop.addOrder(a);
    shop.addOrder(b);
    shop.addOrder(c);
    shop.addOrder(d);
    shop.addOrder(e);
    shop.addOrder(f);
    shop.addOrder(g);
    return shop;
}
```

2022-11-09 19:11 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +    public void initializeShop() {
shop = initShop();

2022-11-09 19:11 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +    Shop shop = new Shop();
private Shop shop;

2022-11-09 19:11 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +        assertEquals(Set.of(a, b, c), shop.getOrderByDateRange(LocalDate.of(2022,1,1),
```
// given
Set<Order> expectedResult = Set.of(new Order(250, LocalDate.of(2022,11,7), "Art07"), new Order(50.50, LocalDate.of(2022,5,10), "Bar12"), new Order(2500.40, LocalDate.of(2022,2,15), "ano"));
// when then
assertEquals(expectedResult, shop.getOrderByDateRange(....));
```

2022-11-10 17:11 UTC, artcor77 commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +    public void shouldReturnCorrectOrdersListSize() {   //Teraz jest dobra ilosc pomimo zduplikowanych elementów w zbiorze(equals & hash)
Ma sens coś takiego, czy wywalic bo niepotrzebne ?

2022-11-10 18:49 UTC, mps4dev requested changes

2022-11-10 18:49 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +        Order lidl = new Order(250, LocalDate.of(2022, 11, 7), "Art07");
order1, order2, order3... Zadnych polskich slow w kodzie :)

2022-11-10 18:49 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +    public void shouldReturnCorrectOrdersListSize() {   //Teraz jest dobra ilosc pomimo zduplikowanych elementów w zbiorze(equals & hash)
Ok

2022-11-10 18:49 UTC, mps4dev commented on kodilla-advanced-tests/src/test/java/com/kodilla/execution_model/homework/ShopTestSuite.java
> +        assertEquals(3901.5, initShop().sumOfOrdersValue());
Czu wywolujes initShop? shop wystaczy przeciez

2022-11-11 18:40 UTC, mps4dev approved these changes

2022-11-12 17:52 UTC, merged