3.2-KOD-Klasy abstrakcyjne-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #5
Opened 2022-10-04 13:40 UTC by artcor77

2022-10-04 13:59 UTC, mps4dev requested changes

2022-10-04 13:59 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Circle.java
> +    static final double PI = 3.1415927;
Zastosuj stala z pakietu math

2022-10-04 13:59 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/AutomationTester.java
> +    public void whatResponsibilities() {
PrintResponsibilities jak juz

2022-10-04 13:59 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Circle.java
> +    public void calculateCircuit() {
Metody maja miec jedna odpowiedzialnosc - proponuje, by metoda obliczajaca obliczala i zwracala wynik. Wydrukujesz sobie wybik w metodzie main.

2022-10-04 13:59 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/AutomationTester.java
> +    public AutomationTester(){
Po co ci dwa konstrukyory?

2022-10-05 19:57 UTC, mps4dev requested changes

2022-10-05 19:57 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Doctor.java
> +    public void PrintResponsibilities() {
Nazwy metod z malej litery

2022-10-05 19:57 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Job.java
> +public abstract void PrintResponsibilities();
brak wciecia

2022-10-05 19:57 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Job.java
> +public abstract void PrintResponsibilities();
metoda z malej litery - ale ta metoda ci nie jest potrzebna

2022-10-05 19:57 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/abstracts/homework/Person.java
> +        Person person = new Person("Adam",30,"Taxi Driver");
```
public class Person {
    public String firstName;
    public int age;
    public Job job;
  ...
}
```

Person adamKowalski = new Person("Adam Kowalski", 30, new TaxiDriver());
System.out.println(adamKowalski.getJob().getResponsibilities());

reszta podobnie

2022-10-06 17:08 UTC, mps4dev requested changes
PrintResponsibilities???

2022-10-07 16:32 UTC, artcor77 commented
PrintResponsibilities poprawiłem najpierw na małą literę, a później napisałeś, że ta metoda niepotrzebna jest, to usunąłem i dałem te gettery.

2022-10-07 17:16 UTC, mps4dev approved these changes

2022-10-08 18:12 UTC, merged