KOD-8.6-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #53
Opened 2022-11-20 17:46 UTC by artcor77

2022-11-20 17:48 UTC, artcor77 commented
![image](https://user-images.githubusercontent.com/113117950/202917626-e526a860-e72a-4f89-8795-fd7fc7a85f4a.png)
...
![image](https://user-images.githubusercontent.com/113117950/202917678-35bcc666-63e4-4066-8ccd-41d9439226e5.png)

2022-11-20 19:01 UTC, mps4dev requested changes

2022-11-20 19:01 UTC, mps4dev commented on kodilla-SQL/src/main/java/KOD-8.6-ZADANIE — kopia.sql
> +WHERE ID = 8;
Skad wiesz, jakie id?

2022-11-20 19:01 UTC, mps4dev commented on kodilla-SQL/src/main/java/KOD-8.6-ZADANIE — kopia.sql
> +WHERE ID = 8;
J.w.

2022-11-22 19:43 UTC, mps4dev approved these changes

2022-11-23 15:09 UTC, merged