KOD-9.2-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #58
Opened 2022-11-23 17:08 UTC by artcor77

2022-11-23 18:59 UTC, mps4dev requested changes
Display, jak sama nazwa wskazuje, ma pokazywac cos :) czyli wyjatkowo ma robic println

2022-11-23 19:05 UTC, mps4dev commented on kodilla-spring-basic/src/test/java/com/kodilla/spring/basic/spring_dependency_injection/homework/CalculatorTestSuite.java
> +    }
assertThrows(() -> bean.divide(2, 0), ArithmeticException.class)

2022-11-23 19:07 UTC, mps4dev commented on kodilla-spring-basic/src/main/java/com/kodilla/spring/basic/spring_dependency_injection/homework/Calculator.java
> +        double div = a / b;
if (b == 0) {
     display.display("Not divide by zero");
     return 0;
}


albo 

try {
     double div = a / b;
     display.display(div);
     return div;
} catch (ArtihmeticException ex) {
     display.display("Not divide by zero");
     return 0;
}

2022-11-23 21:30 UTC, artcor77 commented
Takie rozwiązanie mi jeszcze wpadło bo nie rzucało mi wyjątku Arithmetic
        assertEquals(Double.NaN, bean.divide(10, 0));

2022-11-24 17:50 UTC, mps4dev requested changes
Gdzie asercja z wyjatkiem?

2022-11-24 17:50 UTC, mps4dev commented on kodilla-spring-basic/src/main/java/com/kodilla/spring/basic/spring_dependency_injection/homework/Display.java
> +        System.out.println(value);
Dospaly ma robic dispaly. Ma nic nie zeracac.

2022-11-24 18:49 UTC, artcor77 commented
Pisałem wcześniej o wyjątku. Nie szło z assertThrows(Arithmetic....)
Wczesniej błędy wynikały z NaN (0/0) i Infinity (10/0)

Wyczytałem że dla float i double można użyć :
       assertEquals(Double.NaN, bean.divide(0, 0))
       assertEquals(Double.POSITIVE_INFINITY, bean.divide(10, 0))
To działa i tez jest proste.

2022-11-24 19:24 UTC, mps4dev requested changes
Ale to nie zadziala

2023-01-04 19:15 UTC, merged