3.6-KOD-Podstawy JUnit-ZADANIE
artcor77/artur_lukasiewicz-kodilla_tester pull request #9
Opened 2022-10-06 15:15 UTC by artcor77

Trzeba stworzyć osobną metodę z deltą, czy wystarczy jej użyć, tak, jak zrobiłem to ?

2022-10-06 17:05 UTC, mps4dev requested changes

2022-10-06 17:05 UTC, mps4dev commented on kodilla-basic-tests/src/test/java/com/kodilla/basic_assertion/CalculatorTestSuite.java
> +        assertEquals(25, exponentiationResult, 0.001);
Tu zbedne sa te delty - przy liczbach calkowitych kokputer sobie dobrze radzi

2022-10-06 17:05 UTC, mps4dev commented on kodilla-basic-tests/src/test/java/com/kodilla/basic_assertion/CalculatorTestSuite.java
> +        assertEquals(0, exponentiationResultZero,0.001);
Gdzie pozostale przypadki? Np 2 do -5? Tu sie delta przyda.

2022-10-07 16:47 UTC, artcor77 commented on kodilla-basic-tests/src/test/java/com/kodilla/basic_assertion/CalculatorTestSuite.java
> +        assertEquals(25, exponentiationResult, 0.001);
Tak, wiem, ale samo użycie jest OK ?

2022-10-07 16:47 UTC, artcor77 commented on kodilla-basic-tests/src/test/java/com/kodilla/basic_assertion/CalculatorTestSuite.java
> +        assertEquals(0, exponentiationResultZero,0.001);
"W trakcie potęgowania uwzględnij przypadek liczby mniejszej od zera, zera i liczby większej od zera." - zrozumiałem, że chodzi o liczby, które będą potęgowane.

2022-10-07 17:17 UTC, mps4dev commented on kodilla-basic-tests/src/test/java/com/kodilla/basic_assertion/CalculatorTestSuite.java
> +        assertEquals(25, exponentiationResult, 0.001);
Uzycie tak

2022-10-07 17:18 UTC, mps4dev approved these changes

2022-10-08 18:13 UTC, merged